server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/authentication/**

        - id: authentication-service-secured
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/activation/**,/api/v1/logout
          filters:
            - Authentication
eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_URL:localhost:8761}/eureka

services:
  authentication-service:
    name: authentication-service
