server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/register/**,/api/v1/login/**

        - id: authentication-service-secured
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/confirm/**,/api/v1/confirmation-code/**,/api/v1/logout
          filters:
            - Authentication
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/user/**
          filters:
            - Authentication

        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/api/v1/chat/**
          filters:
            - Authentication

        - id: websocket-server
          uri: lb://websocket-server
          predicates:
            - Path=/ws/**,/chat/**,/user/**
          filters:
            - Authentication
eureka:
  client:
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_URL:localhost:8761}/eureka

services:
  authentication-service:
    name: authentication-service
