server:
  port: ${SERVER_PORT:0}

spring:
  application:
    name: user-service
  neo4j:
    uri: bolt://${DATABASE_URL:localhost:7687}
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: user-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    retry:
      topic:
        enabled: true
    listener:
      concurrency: 10

logging:
  level:
    org:
      springframework:
        data:
          neo4j: ERROR

eureka:
  client:
    service-url:
      defaultZone: http://${DISCOVERY_SERVER_URL:localhost:8761}/eureka
  instance:
    prefer-ip-address: true

kafka:
  topics:
    registration-topic: registration-topic
    user-update-topic: user-update-topic
